- op: replace
  path: /spec/ports/0
  value:
    name: https
    targetPort: 8443
    port: 443
- op: replace
  path: /spec/type
  value: LoadBalancer
- op: add
  path: /metadata/annotations
  value:
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:us-west-2:941892620273:certificate/d501903f-30d2-46d7-8de4-75dd19b3db40
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: ssl
