# Customizations can be found here: https://zero-to-jupyterhub.readthedocs.io/en/latest/jupyterhub/customizing/user-environment.html

jupyterhub:
  hub:
    config:
      Auth0OAuthenticator:
        client_id: zwLsZdOmbKRat6i5Ccm7pq8vfNSNZNvR
        client_secret:
        oauth_callback_url: http://notebook.eventualcomputing.com/hub/oauth_callback
        scope:
          - openid
          - email
        auth0_subdomain: dev-kn2voyk3.us
      Authenticator:
        admin_users:
          - jay@eventualcomputing.com
          - sammy@eventualcomputing.com
        allowed_users:
          - jaychia94@gmail.com
          - sammy.sidhu@gmail.com
          - will@coactive.ai
        auto_login: true
      JupyterHub:
        authenticator_class: auth0

    # Extra config specified as Python
    # https://zero-to-jupyterhub.readthedocs.io/en/latest/administrator/advanced.html#hub-extraconfig
    #
    # TODO(jaychia): We can make an API request here to retrieve a list of images for profiles
    # Also, version 4.1 of KubeSpawner (May 19 2022) makes this much nicer with a dropdown menu
    # within a single profile. We should move to that once it becomes available in a new release
    # of JupyterHub Kubernetes.
    extraConfig:
      00-env-profiles: |
        def get_profiles(spawner):
          return [
            {
              "display_name": "Daft notebook",
              "description": "Notebook with Daft installed and environment: My Default Environment",
              "kubespawner_override": {
                "image": "941892620273.dkr.ecr.us-west-2.amazonaws.com/daft/notebook:0.0.6rc0",
              },
              "default": True,
            },
            {
              "display_name": "Daft notebook",
              "description": "Notebook with Daft installed and environment: My Environment 2",
              "kubespawner_override": {
                "image": "941892620273.dkr.ecr.us-west-2.amazonaws.com/daft/notebook:0.0.6rc0",
              },
            },
          ]
        c.KubeSpawner.profile_list = get_profiles

  proxy:
    https:
      enabled: true
      hosts:
        - notebook.eventualcomputing.com
      letsencrypt:
        contactEmail: sammy@eventualcomputing.com

  singleuser:
    # All notebooks spawned will use this service account
    serviceAccountName: daft

    # Modify the default PVC path to our daftuser $HOME instead
    storage:
      homeMountPath: /home/daftuser

    extraEnv:
      DAFT_WORKDIR: /home/daftuser
      DAFT_REQUIREMENTS_TXT: /opt/daft/requirements.txt
      DAFT_CLUSTER_HEAD_ADDR: ray://default-ray-head-svc.ray:10001
      DAFT_DATAREPOS_BUCKET: eventual-data-test-bucket
      DAFT_DATAREPOS_PREFIX: datarepos
