# Customizations can be found here: https://zero-to-jupyterhub.readthedocs.io/en/latest/jupyterhub/customizing/user-environment.html

jupyterhub:
  hub:
    config:
      Auth0OAuthenticator:
        client_id: zwLsZdOmbKRat6i5Ccm7pq8vfNSNZNvR
        client_secret:
        oauth_callback_url: http://notebook.eventualcomputing.com/hub/oauth_callback
        scope:
          - openid
          - email
        auth0_subdomain: dev-kn2voyk3.us
      Authenticator:
        admin_users:
          - jay@eventualcomputing.com
          - sammy@eventualcomputing.com
        allowed_users:
          - jaychia94@gmail.com
          - sammy.sidhu@gmail.com
          - will@coactive.ai
        auto_login: true
      JupyterHub:
        authenticator_class: auth0

  proxy:
    https:
      enabled: true
      hosts:
        - notebook.eventualcomputing.com
      letsencrypt:
        contactEmail: sammy@eventualcomputing.com

  singleuser:
    # All notebooks spawned will use this service account
    serviceAccountName: daft

    # Defines the default image
    image:
      name: jupyter/minimal-notebook
      tag: latest

    profileList:
      - display_name: "Daft notebook"
        description: "Notebook with Daft installed and ready to go"
        kubespawner_override:
          image: 941892620273.dkr.ecr.us-west-2.amazonaws.com/daft/notebook:0.0.1
      - display_name: "Minimal environment"
        description: "Minimal environment for running just Python"
        default: true

    # Modify the default PVC path to our daftuser $HOME instead
    storage:
      homeMountPath: /home/daftuser
