[tool.poetry]
name = "daft"
version = "0.1.0"
description = "Eventual daft"
authors = ["Eventual Inc <founders@eventualcomputing.com>"]
license = "Copyright Eventual Inc 2022"

[tool.poetry.dependencies]
python = "^3.8"
ray = "^1.12.0"
numpy = "^1.22.3"
pyarrow = "^8.0.0"


[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
