[tool.poetry]
name = "daft"
version = "0.1.0"
description = "Eventual daft"
authors = ["Eventual Inc <founders@eventualcomputing.com>"]
license = "Copyright Eventual Inc 2022"

[tool.poetry.dependencies]
python = "^3.8"
ray = "^1.12.0"
numpy = "^1.22.3"
pyarrow = "^8.0.0"
boto3 = "^1.23.0"
Pillow = "^9.1.0"
torch = "^1.11.0"
torchvision = "^0.12.0"

[tool.poetry.dev-dependencies]
pytest = "^7.1.2"
mypy = "^0.950"
boto3-stubs = "^1.23.0"
types-Pillow = "^9.0.15"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"


[tool.mypy]
python_version = "3.8"
files = ["daft/**/*.py", "tests/**/*.py"]
warn_return_any = true
warn_unused_configs = true
