kind: Deployment
apiVersion: apps/v1
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      name: frontend-app
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: localhost:5001/eventual-hub-frontend:latest
        ports:
        - containerPort: 3000
          name: frontend-port
