apiVersion: v2
name: daft-jupyterhub
description:  Daft Jupyterhub deployment
type: application
version: 0.1.0
appVersion: "0.1.0"
dependencies:
- name: jupyterhub
  version: "1.2.0"
  repository: "https://jupyterhub.github.io/helm-chart/"
